JavaCohort3/ZipCodeBank

src/main/java/com/example/javacohort3/ZipCodeBank/Customer.java
=> Customer Class updated

src/main/java/com/example/javacohort3/ZipCodeBank/Address.java
=> made new address class

src/main/java/com/example/javacohort3/ZipCodeBank/Withdrawals.java
I made the POJO as asked and both of the constructors (One default and one with all the variables) as asked and on time
=> here is my Withdrawals POJO

src/main/java/com/example/javacohort3/ZipCodeBank/accountType.java
=> added enum

src/main/java/com/example/javacohort3/ZipCodeBank/service/AccountService.java
Added getCustomerById() in AccountService.java
=> Updated AccountService.java

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/BillController.java
=> added BillController

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Bill.java
Hello SM,
I've added the second constructor as asked
JoJo
=> Second Bill Constructor

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/CustomerController.java, src/main/java/com/example/javacohort3/ZipCodeBank/repositories/AccountRepository.java, src/main/java/com/example/javacohort3/ZipCodeBank/repositories/CustomerRepository.java
noticed some more import issues fixed those as well
=> fixed errors

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Withdrawal.java
Added:
-instance variables
-default constructor
-regular constructor
-getters
-setters
-toString method
=> First commit, added Withdrawal POJO

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Customer.java
Dear SM, 
Here is my Final Customer POJO. I apologize for the errors but they have been fixed.
JoJo
=> Jo jo final task2 02 customer pojo

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Customer.java
Dear SM,
I have created my POJO as requested.
JoJo
=> The Customer POJO - JoJo

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Address.java, src/main/java/com/example/javacohort3/ZipCodeBank/domains/Customer.java
Dear SM, 
Here is the Address POJO you requested. 
JoJo
=> Jo jo task2 23 address pojo

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Deposit.java
added account_id of type java.lang.Long
=> Updated Deposit.java

src/main/java/com/example/javacohort3/ZipCodeBank/repositories/WithdrawalRepository.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/WithdrawalService.java
Added:
-public interface WithdrawalRepository extends CRUDRepository<WIthdrawal, Long>{}
-necessary imports
=> First commit, added WithdrawalRepository Interface

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Withdrawal.java
-Added account_id instance variable
-Updated constructor with account_id
-Updated getters and setters with account_id
-Updated toString method with account_id
=> First commit, updated Withdrawal POJO

pom.xml, src/main/java/com/example/javacohort3/ZipCodeBank/Status.java, src/main/java/com/example/javacohort3/ZipCodeBank/controllers/BillController.java, src/main/java/com/example/javacohort3/ZipCodeBank/domains/Bill.java, src/main/java/com/example/javacohort3/ZipCodeBank/repositories/BillRepository.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/BillService.java
Task 03 Bill service, pojo, & repo completed
=> Task 03 Bill service, pojo, & repo completed

src/main/java/com/example/javacohort3/ZipCodeBank/controller/CustomerController.java, src/main/java/com/example/javacohort3/ZipCodeBank/repositories/CustomerRepository.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/CustomerService.java
Dear SM,
Here is my new Repository
JoJo
=> Task2 17 jojo customer repo

src/main/java/com/example/javacohort3/ZipCodeBank/controller/CustomerController.java, src/main/java/com/example/javacohort3/ZipCodeBank/repositories/CustomerRepository.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/CustomerService.java
Dear SM,
Here is my CustomerRepository interface as requested
JoJo
=> Jojo task2 17 customer repository

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Customer.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/CustomerService.java
Dear SM,
Here is my new POJO.
JoJo
=> Heres the new Customer POJO

src/main/java/com/example/javacohort3/ZipCodeBank/services/CustomerService.java
Dear SM,
Here is my Completed CustomerService Class, sorry for any delays
JoJo
=> Here is my CustomerService Class

src/main/java/com/example/javacohort3/ZipCodeBank/services/WithdrawalService.java
Added:
-@Service annotation
-AccountRepository and WithdrawalRepository instance variables
-@Autowired annotation
-Constructor
-verifyAccount method
-verifyWithdrawal method
-createWithdrawalFromAccount method
-getWithdrawalById method
-getAllWithdrawalsForAccountId method
-updateWIthdrawal method
-deleteWithdrawal method
Removed:
=> First commit, added methods into WithdrawalService

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/DepositController.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/DepositService.java, src/test/java/com/example/javacohort3/ZipCodeBank/DepositControllerTest.java
DepositController & DepositService
=> Added DepositControllerTest & updated other files

src/test/java/com/example/javacohort3/ZipCodeBank/BillControllerTest.java
Controller Test added for BillController
=> Controller Test added for BillController

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/WithdrawalController.java
Added:
-WithdrawalService instance variable
-constructor
-getAllWithdrawalsForAccountId method with necessary annotations
-getWithdrawalById method with necessary annotations
-createWithdrawalFromAccount method with necessary annotations
-updateDWithdrawalFromAccountId method with necessary annotations
-deleteWithdrawalById method with necessary annotations
=> 10 withdrawal controller

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/CustomerController.java
Dear SM,
I have fixed my updateCustomer( ) to use the verify method
JoJo
=> Here is the updated CustomerController

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/CustomerController.java, src/test/java/com/example/javacohort3/ZipCodeBank/CustomerControllerTests.java
Dear Sm,
Here is my Testing as requested, they all passed
JoJo
=> Testing 2 JoJo customer

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Address.java, src/main/java/com/example/javacohort3/ZipCodeBank/domains/Customer.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/CustomerService.java
Dear SM,
Here are my corrections, if there's anything wrong let me know.
JoJo
=> Here are my corrections

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/AccountController.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/AccountService.java, src/test/java/com/example/javacohort3/ZipCodeBank/AccountControllerTest.java
had to fix some parts of my account controller and account services in order to get my tests passing.
=> Made tests

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/AccountController.java, src/main/java/com/example/javacohort3/ZipCodeBank/domains/Account.java
fixed accountcontroller and account pojo
=> small fixes

src/main/java/com/example/javacohort3/ZipCodeBank/repositories/DepositRepository.java
created the Deposit Repository interface
=> Added Deposit Repository

src/main/java/com/example/javacohort3/ZipCodeBank/repositories/WithdrawalRepository.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/WithdrawalService.java
Added:
-WithdrawalRepository
-WithdrawalService
=> P3 Withdrawals Repository and Service

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/CustomerController.java, src/main/java/com/example/javacohort3/ZipCodeBank/exceptions/ResponseDetails.java
*Reverts JavaCohort3/ZipCodeBank#105*
=> Revert "Claude response details"

src/main/java/com/example/javacohort3/ZipCodeBank/repositories/WithdrawalRepository.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/WithdrawalService.java
Added:
-Withdrawal class import for WithdrawalService
-Withdrawal class import for WithdrawalRepository
=> First commit

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/CustomerController.java
each controller method returns only single instance of responseDetails
=> Customer controller

src/main/java/com/example/javacohort3/ZipCodeBank/exceptions/ResponseDetails.java
I was originally trying to make it so that I could use the value method in one place such that I wouldn't have to call the method in multiple places.
=> should have update responsedetails class

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Deposit.java, src/main/java/com/example/javacohort3/ZipCodeBank/domains/Withdrawal.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/DepositService.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/WithdrawalService.java
- tidied getters and setters in deposit and withdrawal pojos
- removed unnecessary variables from deposit service
- updated withdrawal to match deposit
- updated withdrawal service to match deposit service
=> Deposit & Withdrawal Changes

src/main/java/com/example/javacohort3/ZipCodeBank/domains/Bill.java
since the enum name was changed I had to fix the object in the Bill POJO for it to call the correct enum
=> Changed enum Object name

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/BillController.java
=> New Changes in Bill Controller

src/main/java/com/example/javacohort3/ZipCodeBank/services/CustomerService.java
=> getCustomerByAccountId() in CustomerService.java

src/main/java/com/example/javacohort3/ZipCodeBank/services/CustomerService.java
Dear SM Zamir, 
I have fixed the verifyCustomer() and verifyAccount() methods in the CustomerService as asked of me.
Your Worker, 
JoJo
=> I fixed the 2 verify methods as requested of me

src/main/java/com/example/javacohort3/ZipCodeBank/exceptions/ResponseDetails.java
=> Fixed ResponseDetails

src/main/java/com/example/javacohort3/ZipCodeBank/services/AccountService.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/BillService.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/DepositService.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/WithdrawalService.java
Commited the new verify methods to fit required methods as client requested
=> Commited the new verify methods

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/CustomerController.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/CustomerService.java, src/main/java/com/example/javacohort3/ZipCodeBank/util/Burn.java
static method `Burn.updateObjectFields(Object newObject, Object oldObject)` where `newObject` is the object that will be saved to the repository and `oldObject` is the object that is already in the given repository.
For all the values in the `newObject` that are null, this method takes the respective values from `oldObject`. Both must be the same object type.
Works with all classes.
=> Created update utility

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/BillController.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/BillService.java
Reverts JavaCohort3/ZipCodeBank#171
=> Revert "Update Bill"

src/main/java/com/example/javacohort3/ZipCodeBank/controllers/DepositController.java, src/main/java/com/example/javacohort3/ZipCodeBank/services/DepositService.java
Removed:
-all verify methods from the DepositController class
Added:
-all verify methods to the DepositService Class
-necessary usage of the Burn class' updateObjectFields method within the updateDeposit method inside of the DepositService class
=> Made changes to Deposit Controller and Service
